version: 2
updates:

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/**"
    schedule:
      interval: "daily"
      time: "01:46"
      timezone: "Europe/Berlin"
    groups:
      actions-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
