version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:46"
      timezone: "Europe/Berlin"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/setup"
    schedule:
      interval: "daily"
      time: "01:46"
      timezone: "Europe/Berlin"
