name:
  Setup
description:
  Setup of the needed software

inputs:
  os:
    description: The os for the run.
    required: true

  cxx:
    description: The c++ compiler to use.
    required: true

outputs:
  ccache-variant:
    description: The ccache variant to use with the ccache-action
    value: ${{ steps.determine-ccache-variant.outputs.ccache-variant }}

runs:
  using: composite
  steps:
    - id: determine-ccache-variant
      shell: bash
      run: |
        echo "ccache-variant=${{ ( (runner.os == 'Windows') && 'sccache' ) || 'ccache' }}"  >> $GITHUB_OUTPUT

    - name: Setup CCache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ inputs.os }}-${{ inputs.cxx }}--${{ github.job }}
        restore-keys: |
          ${{ inputs.os }}-${{ inputs.cxx }}--${{ github.job }}
          ${{ inputs.os }}-${{ inputs.cxx }}
          ${{ inputs.os }}
        variant: ${{ steps.determine-ccache-variant.outputs.ccache-variant }}

    - name: Setup Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt update
        sudo apt install ninja-build

    - name: Setup macOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install ninja

    - name: Setup Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        choco install -y ninja

    - name: Set up Visual Studio shell on Windows
      uses: TheMrMilchmann/setup-msvc-dev@v3
      if: runner.os == 'Windows'
      with:
        arch: x64
