name:
  Setup
description:
  Setup of the needed software

inputs:
  os:
    description: The os for the run.
    required: true

  cxx:
    description: The c++ compiler to use.
    required: true

outputs:
  ccache-variant:
    description: The ccache variant to use with the ccache-action
    value: ${{ steps.determine-ccache-variant.outputs.ccache-variant }}

runs:
  using: composite
  steps:
    - id: determine-ccache-variant
      shell: bash
      run: |
        echo "ccache-variant=${{ ( (runner.os == 'Windows') && 'sccache' ) || 'ccache' }}"  >> $GITHUB_OUTPUT

    - name: Setup CCache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ inputs.os }}-${{ inputs.cxx }}--${{ github.job }}
        restore-keys: |
          ${{ inputs.os }}-${{ inputs.cxx }}--${{ github.job }}
          ${{ inputs.os }}-${{ inputs.cxx }}
          ${{ inputs.os }}
        variant: ${{ env.CMAKE_CXX_COMPILER_LAUNCHER }}

    - name: Setup Linux variables
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin"                                                           >> $GITHUB_PATH

    - name: Setup Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ccache ninja-build

        brew update
        brew install boost

    - name: Setup macOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install ninja boost

    - name: Setup Windows variables
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Write "BOOST_DOWNLOAD_URI=https://downloads.sourceforge.net/project/boost/boost-binaries/1.85.0/boost_1_85_0-msvc-14.3-64.exe"  >> $env:GITHUB_ENV
        Write "BOOST_INSTALLER_PATH=$env:RUNNER_TEMP\boost.exe"                                                                         >> $env:GITHUB_ENV
        Write "BOOST_ROOT=$env:RUNNER_TEMP\boost"                                                                                       >> $env:GITHUB_ENV

    - name: Setup Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Start-BitsTransfer -Source $env:BOOST_DOWNLOAD_URI -Destination $env:BOOST_INSTALLER_PATH
        Start-Process -Wait -FilePath "$env:BOOST_INSTALLER_PATH" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=$env:BOOST_ROOT"

        choco install -y ninja

    - name: Set up Visual Studio shell on Windows
      uses: TheMrMilchmann/setup-msvc-dev@v3
      if: runner.os == 'Windows'
      with:
        arch: x64
