// SPDX-FileCopyrightText: 2025 Ralf Konrad Eckel
// SPDX-License-Identifier: MIT

#ifndef MCBONUSCLASSICENGINE_HPP
#define MCBONUSCLASSICENGINE_HPP

#include <rke/ql/ext/instruments/BonusClassicOption.hpp>
#include <rke/ql/ext/methods/montecarlo/BlackScholesPathGenerator.hpp>
#include <ql/pricingengines/barrier/mcbarrierengine.hpp>
#include <ql/pricingengines/mcsimulation.hpp>
#include <ql/processes/blackscholesprocess.hpp>

namespace RKE::QL::Ext {
    //! Pricing engine for bonus certificates using Monte Carlo simulation
    /*! Paths of the underlying are generated by a
        QuantLib::GeneralizedBlackScholesProcess on an equally spaced time
        grid from the evaluation date to the exercise date. A spot already at
        or below the barrier makes calculate() throw instead of pricing a
        knocked-out certificate. The path pricer is selected by isBiased:

        - true: BiasedBonusClassicPathPricer monitors the barrier discretely,
          on the grid points after \f$ t = 0 \f$, the last one being
          maturity. No Brownian-bridge correction is applied, so the engine
          prices the discretely monitored product, whose value lies above
          that of the continuously monitored one.
        - false: BonusClassicPathPricer monitors the barrier continuously by
          weighting each path with its Brownian-bridge probability of
          surviving every grid step. It draws no extra random numbers.

        Residual time and the grid are measured with the process's
        QuantLib::GeneralizedBlackScholesProcess::time(), i.e. the day
        counter of its risk-free curve, and the payoff is discounted on that
        curve from maturity. Dividends enter through the process's drift.
        Neither antithetic variates nor a control variate are used.

        Paths come from BlackScholesPathGenerator, which takes the process's
        exact step from terms computed once per grid where the volatility is
        strike-independent, and calls its evolve() otherwise. The paths are
        the doubles QuantLib::PathGenerator would produce.

        \warning with isBiased = false the bridge is exact only for a
                 strike-independent volatility. Under a smile or local
                 volatility, QuantLib::GeneralizedBlackScholesProcess::variance()
                 falls back to its discretization and the survival
                 probability is an approximation.
        \warning with RNG = QuantLib::LowDiscrepancy no error estimate is
                 available: requiredTolerance has to be Null<Real>() and
                 errorEstimate() is not set.

        \ingroup barrierengines

        \test the correctness of the discretely monitored value is tested
              by replicating the certificate with the asset and a
              down-and-out put priced with QuantLib::AnalyticBarrierEngine,
              corrected for discrete monitoring after Broadie, Glasserman
              and Kou (1997).
        \test the correctness of the continuously monitored value is tested
              by the same replication at the uncorrected barrier.
        \test both values are regression-locked for a fixed seed, sample
              count and grid under QuantLib::LowDiscrepancy.
        \test the continuously monitored value is checked to lie below the
              discretely monitored one on the same grid and seed.
    */
    template <class RNG = QuantLib::PseudoRandom, class S = QuantLib::Statistics>
    class MCBonusClassicEngine : public BonusClassicOption::engine,
                                 public QuantLib::McSimulation<BlackScholesSingleVariate, RNG, S> {
      public:
        using path_generator_type =
            typename QuantLib::McSimulation<BlackScholesSingleVariate, RNG, S>::path_generator_type;
        using path_pricer_type =
            typename QuantLib::McSimulation<BlackScholesSingleVariate, RNG, S>::path_pricer_type;
        using stats_type =
            typename QuantLib::McSimulation<BlackScholesSingleVariate, RNG, S>::stats_type;

        /*! \param process          the underlying; the engine registers with it
            \param timeStepsPerYear grid density; the grid has
                                    max(floor(timeStepsPerYear * T), 1) steps
                                    for residual time \f$ T \f$, and
                                    Null<Size>() fails at calculation
            \param requiredSamples  number of paths when no tolerance is given
            \param maxSamples       upper bound on paths when a tolerance is given
            \param requiredTolerance target error estimate, or Null<Real>() to
                                    run requiredSamples paths
            \param isBiased         true monitors the barrier on the grid
                                    points, false continuously through the
                                    Brownian-bridge survival probability
            \param brownianBridge   whether paths are built with a Brownian
                                    bridge (affects path construction, not the
                                    barrier check)
            \param seed             seed of the sequence generator
        */
        MCBonusClassicEngine(
            QuantLib::ext::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process,
            QuantLib::Size timeStepsPerYear,
            QuantLib::Size requiredSamples,
            QuantLib::Size maxSamples,
            QuantLib::Real requiredTolerance,
            bool isBiased,
            bool brownianBridge,
            QuantLib::BigNatural seed);

        void calculate() const override;
        QuantLib::ext::shared_ptr<path_pricer_type> pathPricer() const override;
        QuantLib::TimeGrid timeGrid() const override;

      private:
        QuantLib::ext::shared_ptr<path_generator_type> pathGenerator() const override {
            const QuantLib::TimeGrid grid = timeGrid();
            const typename RNG::rsg_type gen = RNG::make_sequence_generator(grid.size() - 1, seed_);
            return QuantLib::ext::make_shared<path_generator_type>(process_, grid, gen,
                                                                   brownianBridge_);
        }

        QuantLib::ext::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process_;
        QuantLib::Size timeStepsPerYear_;
        QuantLib::Size requiredSamples_;
        QuantLib::Size maxSamples_;
        QuantLib::Real requiredTolerance_;
        bool isBiased_;
        bool brownianBridge_;
        QuantLib::BigNatural seed_;
    };

    //! Path pricer for bonus certificates monitored on the path's grid points
    /*! Returns the discounted final price \f$ S_T \f$ of the path if any point
        after \f$ t = 0 \f$ is at or below the barrier, and the discounted
        BonusClassicPayoff of \f$ S_T \f$ otherwise. It is "biased" in the
        sense of QuantLib::BiasedBarrierPathPricer: crossings between grid
        points go unseen.
    */
    class BiasedBonusClassicPathPricer : public QuantLib::PathPricer<QuantLib::Path> {
      public:
        /*! \param discountFactor risk-free discount factor from maturity to
                                  the evaluation date
            \pre barrier and bonus level of \p payoff are positive.
        */
        BiasedBonusClassicPathPricer(BonusClassicPayoff payoff,
                                     QuantLib::DiscountFactor discountFactor);
        QuantLib::Real operator()(const QuantLib::Path& path) const override;

      private:
        BonusClassicPayoff payoff_;
        QuantLib::DiscountFactor discountFactor_;
    };

    //! Path pricer for bonus certificates monitored continuously
    /*! Returns the discounted final price \f$ S_T \f$ of the path if any
        point after \f$ t = 0 \f$ is at or below the barrier \f$ H \f$.
        Otherwise the barrier may still have been crossed between grid
        points; conditional on the endpoints of step \f$ i \f$, the
        log-price is a Brownian bridge and the crossing probability is
        \f[
            p_i = \exp\left(-\frac{2 \ln(S_i/H) \ln(S_{i+1}/H)}{v_i}\right),
        \f]
        where \f$ v_i \f$ is the integrated variance of the step, taken from
        QuantLib::GeneralizedBlackScholesProcess::variance(); \f$ p_i = 0 \f$
        if \f$ v_i \le 0 \f$. With the survival probability
        \f$ P = \prod_i (1 - p_i) \f$ the path pays
        \f[
            S_T + P \left(\max(S_T, B) - S_T\right),
        \f]
        discounted, i.e. its conditional expectation of the payoff of the
        continuously monitored certificate.

        Unlike QuantLib::BarrierPathPricer it draws no random number of its
        own, so a low-discrepancy path sequence stays intact, and the payoff
        is smooth in the path.

        See P. Glasserman, <i>Monte Carlo Methods in Financial
        Engineering</i>, Springer 2004, on Brownian interpolation of
        barrier crossings, and
        <i>
        Going to Extremes: Correcting Simulation Bias in Exotic
        Option Valuation - D.R. Beaglehole, P.H. Dybvig and G. Zhou
        Financial Analysts Journal; Jan/Feb 1997; 53, 1. pg. 62-68
        </i>
    */
    class BonusClassicPathPricer : public QuantLib::PathPricer<QuantLib::Path> {
      public:
        /*! \param discountFactor risk-free discount factor from maturity to
                                  the evaluation date
            \param process        the process the paths were generated with;
                                  its variance() gives \f$ v_i \f$
            \pre barrier and bonus level of \p payoff are positive.
        */
        BonusClassicPathPricer(
            BonusClassicPayoff payoff,
            QuantLib::DiscountFactor discountFactor,
            QuantLib::ext::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process);
        QuantLib::Real operator()(const QuantLib::Path& path) const override;

      private:
        BonusClassicPayoff payoff_;
        QuantLib::DiscountFactor discountFactor_;
        QuantLib::ext::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process_;
    };


    template <class RNG, class S>
    MCBonusClassicEngine<RNG, S>::MCBonusClassicEngine(
        QuantLib::ext::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process,
        QuantLib::Size timeStepsPerYear,
        QuantLib::Size requiredSamples,
        QuantLib::Size maxSamples,
        QuantLib::Real requiredTolerance,
        bool isBiased,
        bool brownianBridge,
        QuantLib::BigNatural seed)
    : QuantLib::McSimulation<BlackScholesSingleVariate, RNG, S>(false, false),
      process_(std::move(process)), timeStepsPerYear_(timeStepsPerYear),
      requiredSamples_(requiredSamples), maxSamples_(maxSamples),
      requiredTolerance_(requiredTolerance), isBiased_(isBiased), brownianBridge_(brownianBridge),
      seed_(seed) {
        // Without this, NPV() keeps returning the first price.
        registerWith(process_);
    }

    template <class RNG, class S>
    void MCBonusClassicEngine<RNG, S>::calculate() const {
        const auto spot = process_->x0();
        QL_REQUIRE(spot > 0.0, "negative or null underlying given");
        // The path pricer never inspects path[0], so an already-triggered spot is rejected here.
        QL_REQUIRE(!triggered(spot), "barrier touched");
        QuantLib::McSimulation<BlackScholesSingleVariate, RNG, S>::calculate(
            requiredTolerance_, requiredSamples_, maxSamples_);
        results_.value = this->mcModel_->sampleAccumulator().mean();
        // LowDiscrepancy sets allowsErrorEstimate = 0, and every caller instantiates the engine
        // with it or with traits derived from it.
        if constexpr (RNG::allowsErrorEstimate) {
            results_.errorEstimate = this->mcModel_->sampleAccumulator().errorEstimate();
        }
    }

    template <class RNG, class S>
    QuantLib::ext::shared_ptr<typename MCBonusClassicEngine<RNG, S>::path_pricer_type>
    MCBonusClassicEngine<RNG, S>::pathPricer() const {
        const auto payoff =
            QuantLib::ext::dynamic_pointer_cast<BonusClassicPayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "non-plain payoff given");

        const auto grid = timeGrid();
        // Both pricers pay only at maturity; MCBarrierEngine needs a vector of discount
        // factors only for its rebate.
        const auto discountFactor = process_->riskFreeRate()->discount(grid.back());

        if (isBiased_) {
            return QuantLib::ext::shared_ptr<path_pricer_type>(
                new BiasedBonusClassicPathPricer(*payoff, discountFactor));
        }
        return QuantLib::ext::shared_ptr<path_pricer_type>(
            new BonusClassicPathPricer(*payoff, discountFactor, process_));
    }


    template <class RNG, class S>
    QuantLib::TimeGrid MCBonusClassicEngine<RNG, S>::timeGrid() const {
        const auto residualTime = process_->time(arguments_.exercise->lastDate());
        if (timeStepsPerYear_ != QuantLib::Null<QuantLib::Size>()) {
            // A short residual time truncates steps to 0, and TimeGrid(end, 0) divides by zero;
            // hence the std::max below.
            const auto steps = static_cast<QuantLib::Size>(timeStepsPerYear_ * residualTime);
            // QuantLib::TimeGrid has an initializer_list<Time> constructor, which a braced
            // return selects over TimeGrid(Time, Size), narrowing steps to a Time.
            return QuantLib::TimeGrid( // NOLINT(modernize-return-braced-init-list)
                residualTime, std::max<QuantLib::Size>(steps, 1));
        }
        QL_FAIL("time steps not specified");
    }
}
#endif // MCBONUSCLASSICENGINE_HPP
