// SPDX-FileCopyrightText: 2025 Ralf Konrad Eckel
// SPDX-License-Identifier: MIT

#ifndef MCBONUSCLASSICENGINE_HPP
#define MCBONUSCLASSICENGINE_HPP

#include <rke/ql/ext/instruments/BonusClassicOption.hpp>
#include <rke/ql/ext/methods/montecarlo/BlackScholesStepCache.hpp>
#include <rke/ql/ext/methods/montecarlo/CachedStepPathGenerator.hpp>
#include <ql/pricingengines/barrier/mcbarrierengine.hpp>
#include <ql/pricingengines/mcsimulation.hpp>
#include <ql/processes/blackscholesprocess.hpp>
#include <type_traits>

namespace RKE::QL::Ext {
    class BonusClassicPathPricerBase;

    //! Pricing engine for bonus certificates using Monte Carlo simulation
    /*! Paths of the underlying are generated by a
        QuantLib::GeneralizedBlackScholesProcess on an equally spaced time
        grid from the evaluation date to the exercise date. The path pricer
        is selected by isBiased:

        - true: BiasedBonusClassicPathPricer monitors the barrier discretely,
          on the grid points after \f$ t = 0 \f$, the last one being
          maturity. No Brownian-bridge correction is applied, so the engine
          prices the discretely monitored product, whose value lies above
          that of the continuously monitored one.
        - false: BonusClassicPathPricer monitors the barrier continuously by
          weighting each path with its Brownian-bridge probability of
          surviving every grid step. It draws no extra random numbers.

        Residual time and the grid are measured with the process's
        QuantLib::GeneralizedBlackScholesProcess::time(), i.e. the day
        counter of its risk-free curve, and the payoff is discounted on that
        curve from maturity. Dividends enter through the process's drift.
        Neither antithetic variates nor a control variate are used.

        Beside the price the engine reports two probabilities under the
        process's measure in Instrument::additionalResults(), read with
        Instrument::result<Real>("barrierHitProbability") and
        Instrument::result<Real>("bonusProbability"): the probability that a
        monitoring point after \f$ t = 0 \f$ is at or below the barrier, and
        the probability that the barrier is never hit and \f$ S_T < B \f$,
        i.e. that the bonus is paid. Both are monitored on the same grid as
        the price, by the path pricer isBiased selects, and come from the
        same paths; see BonusClassicPathPricerBase.

        Paths come from the generator of the MC traits. The default,
        CachedStepSingleVariate, builds them with CachedStepPathGenerator,
        which takes the process's exact step from terms computed once per
        grid and refuses a process whose step is not exact: a smile, a
        forced discretization or an external local volatility. Such a
        process takes LocalVolStepSingleVariate, whose generator takes the
        Euler step through LocalVolStepCache, evaluating the local
        volatility once per step instead of twice, and refuses an exact
        step in turn. QuantLib::SingleVariate, i.e. QuantLib::PathGenerator,
        takes every process and is the reference the other two are checked
        against: the exact step gives the same doubles, the Euler step the
        same up to LocalVolStepCache::stepTolerance per step, so the choice
        moves no price beyond rounding. The continuous path pricer follows
        the traits: under CachedStepSingleVariate it takes the step variance
        from the same cache, otherwise from the process.

        \tparam MC Monte Carlo traits naming the path generator:
                   CachedStepSingleVariate for a process whose step is
                   exact, LocalVolStepSingleVariate for one taking the Euler
                   step through a local volatility, QuantLib::SingleVariate
                   for any process.

        \warning calculate() requires the spot above the barrier in either
                 mode and throws otherwise. With isBiased = true that is a
                 restriction, not a knock-out: \f$ t = 0 \f$ is no monitoring
                 date, so a certificate alive today with its spot at or below
                 the barrier has a price, which this engine does not compute.
                 With isBiased = false the bridge needs
                 \f$ \ln(S_0 / H) > 0 \f$.
        \warning with isBiased = false the bridge is exact only for a
                 strike-independent volatility. Under a smile or local
                 volatility, QuantLib::GeneralizedBlackScholesProcess::variance()
                 falls back to its discretization and the survival
                 probability is an approximation.
        \warning with RNG = QuantLib::LowDiscrepancy no error estimate is
                 available: requiredTolerance has to be Null<Real>() and
                 errorEstimate() is not set.

        \ingroup barrierengines

        \test the correctness of the discretely monitored value is tested
              by replicating the certificate with the asset and a
              down-and-out put priced with QuantLib::AnalyticBarrierEngine,
              corrected for discrete monitoring after Broadie, Glasserman
              and Kou (1997).
        \test the correctness of the continuously monitored value is tested
              by the same replication at the uncorrected barrier.
        \test both values are regression-locked for a fixed seed, sample
              count and grid under QuantLib::LowDiscrepancy.
        \test the continuously monitored value is checked to lie below the
              discretely monitored one on the same grid and seed.
        \test both values and both probabilities are checked to be the same
              double under CachedStepSingleVariate and QuantLib::SingleVariate,
              and the same up to rounding under LocalVolStepSingleVariate and
              QuantLib::SingleVariate.
        \test both probabilities are regression-locked for a fixed seed,
              sample count and grid under QuantLib::LowDiscrepancy.
        \test both probabilities are checked against
              QuantLib::AnalyticBinaryBarrierEngine (Haug, <i>The complete
              guide to option pricing formulas</i>, 2nd ed., p. 176 ff.), the
              discretely monitored ones at the Broadie-Glasserman-Kou
              shifted barrier and the continuously monitored ones at the
              barrier itself.
        \test the continuously monitored hit probability is checked to lie
              above the discretely monitored one on the same paths.
    */
    template <class RNG = QuantLib::PseudoRandom,
              class S = QuantLib::Statistics,
              template <class> class MC = CachedStepSingleVariate>
    class MCBonusClassicEngine : public BonusClassicOption::engine,
                                 public QuantLib::McSimulation<MC, RNG, S> {
      public:
        using path_generator_type =
            typename QuantLib::McSimulation<MC, RNG, S>::path_generator_type;
        using path_pricer_type = typename QuantLib::McSimulation<MC, RNG, S>::path_pricer_type;
        using stats_type = typename QuantLib::McSimulation<MC, RNG, S>::stats_type;

        /*! \param process          the underlying; the engine registers with it
            \param timeStepsPerYear grid density; the grid has
                                    max(floor(timeStepsPerYear * T), 1) steps
                                    for residual time \f$ T \f$, and
                                    Null<Size>() fails at calculation
            \param requiredSamples  number of paths when no tolerance is given
            \param maxSamples       upper bound on paths when a tolerance is given
            \param requiredTolerance target error estimate, or Null<Real>() to
                                    run requiredSamples paths
            \param isBiased         true monitors the barrier on the grid
                                    points, false continuously through the
                                    Brownian-bridge survival probability
            \param brownianBridge   whether paths are built with a Brownian
                                    bridge (affects path construction, not the
                                    barrier check)
            \param seed             seed of the sequence generator
            \pre \p process is not null; QL_REQUIRE checks this.
        */
        MCBonusClassicEngine(
            QuantLib::ext::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process,
            QuantLib::Size timeStepsPerYear,
            QuantLib::Size requiredSamples,
            QuantLib::Size maxSamples,
            QuantLib::Real requiredTolerance,
            bool isBiased,
            bool brownianBridge,
            QuantLib::BigNatural seed);

        void calculate() const override;
        QuantLib::ext::shared_ptr<path_pricer_type> pathPricer() const override;
        //! the monitoring grid
        /*! \pre the instrument has set up the arguments, i.e. NPV() has run once;
                 QL_REQUIRE checks this. */
        QuantLib::TimeGrid timeGrid() const override;

      private:
        QuantLib::ext::shared_ptr<path_generator_type> pathGenerator() const override {
            const QuantLib::TimeGrid grid = timeGrid();
            const typename RNG::rsg_type gen = RNG::make_sequence_generator(grid.size() - 1, seed_);
            if constexpr (sharesStepCache) {
                return QuantLib::ext::make_shared<path_generator_type>(process_, grid, gen,
                                                                       brownianBridge_, stepCache_);
            } else {
                return QuantLib::ext::make_shared<path_generator_type>(process_, grid, gen,
                                                                       brownianBridge_);
            }
        }

        // Under CachedStepSingleVariate the generator and the continuous path pricer read one
        // BlackScholesStepCache, built per calculation; under the other traits nothing shares.
        static constexpr bool sharesStepCache =
            std::is_same_v<MC<RNG>, CachedStepSingleVariate<RNG>>;

        QuantLib::ext::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process_;
        mutable QuantLib::ext::shared_ptr<const BlackScholesStepCache> stepCache_;
        // The pricer of the current calculation, kept so that calculate() can read the
        // probabilities it accumulated; McSimulation hands it to a model it does not expose.
        mutable QuantLib::ext::shared_ptr<BonusClassicPathPricerBase> pathPricer_;
        QuantLib::Size timeStepsPerYear_;
        QuantLib::Size requiredSamples_;
        QuantLib::Size maxSamples_;
        QuantLib::Real requiredTolerance_;
        bool isBiased_;
        bool brownianBridge_;
        QuantLib::BigNatural seed_;
    };

    //! What the bonus certificate path pricers share
    /*! The payoff, the discount factor from maturity, and the knock-out test
        on the grid points after \f$ t = 0 \f$, inclusive at the barrier like
        the payoff. A knocked-out path pays the discounted final price
        \f$ S_T \f$ in every pricer.

        Beside the value, every pricer records per path its contribution to
        two probabilities under the measure the paths were generated in:
        that the barrier is hit, and that the bonus is paid, i.e. the barrier
        is never hit and \f$ S_T < B \f$. A knocked-out path contributes
        \f$ (1, 0) \f$; what a surviving path contributes is up to the
        derived pricer. barrierHitProbability() and bonusProbability() are
        the means over the paths priced so far, unweighted: under
        QuantLib::MonteCarloModel without antithetic variates and with unit
        path weights, as every generator in QuantLib::PseudoRandom and
        QuantLib::LowDiscrepancy sets them, they are the paths of the sample
        accumulator. samples() is the count a caller checks that against.
    */
    class BonusClassicPathPricerBase : public QuantLib::PathPricer<QuantLib::Path> {
      public:
        //! mean contribution to the barrier being hit over the paths priced so far
        /*! \pre at least one path has been priced; QL_REQUIRE checks this. */
        [[nodiscard]] QuantLib::Real barrierHitProbability() const;
        //! mean contribution to the bonus being paid over the paths priced so far
        /*! \pre at least one path has been priced; QL_REQUIRE checks this. */
        [[nodiscard]] QuantLib::Real bonusProbability() const;
        //! the number of paths priced so far
        [[nodiscard]] QuantLib::Size samples() const { return samples_; }

      protected:
        /*! \param discountFactor risk-free discount factor from maturity to
                                  the evaluation date
            \pre barrier and bonus level of \p payoff are positive, as
                 BonusClassicOption::arguments::validate() ensures; not
                 checked here.
        */
        BonusClassicPathPricerBase(BonusClassicPayoff payoff,
                                   QuantLib::DiscountFactor discountFactor);

        //! whether a grid point after \f$ t = 0 \f$ is at or below the barrier
        /*! \pre the path has at least one step; QL_REQUIRE checks this. */
        [[nodiscard]] bool knockedOut(const QuantLib::Path& path) const;

        //! adds one path's contributions and counts it
        void record(QuantLib::Real hitProbability, QuantLib::Real bonusProbability) const;

        //! the discounted \f$ S_T \f$ of a knocked-out path, recorded as \f$ (1, 0) \f$
        [[nodiscard]] QuantLib::Real knockedOutValue(const QuantLib::Path& path) const;

        //! the discounted value of a surviving path given its survival probability
        /*! \f$ S_T + P \left(\max(S_T, B) - S_T\right) \f$ discounted, recorded
            as \f$ (1 - P, \, P \, 1_{S_T < B}) \f$.
            \pre no grid point after \f$ t = 0 \f$ is at or below the barrier,
                 i.e. knockedOut() is false; not checked here.
        */
        [[nodiscard]] QuantLib::Real continuousValue(const QuantLib::Path& path,
                                                     QuantLib::Real survival) const;

        BonusClassicPayoff payoff_;
        QuantLib::DiscountFactor discountFactor_;

      private:
        mutable QuantLib::Real hitSum_ = 0.0;
        mutable QuantLib::Real bonusSum_ = 0.0;
        mutable QuantLib::Size samples_ = 0;
    };

    //! Path pricer for bonus certificates monitored on the path's grid points
    /*! Returns the discounted final price \f$ S_T \f$ of the path if any point
        after \f$ t = 0 \f$ is at or below the barrier, and the discounted
        BonusClassicPayoff of \f$ S_T \f$ otherwise. It is "biased" in the
        sense of QuantLib::BiasedBarrierPathPricer: crossings between grid
        points go unseen.

        A knocked-out path contributes \f$ (1, 0) \f$ to the probabilities
        of BonusClassicPathPricerBase, a surviving one
        \f$ (0, 1_{S_T < B}) \f$.
    */
    class BiasedBonusClassicPathPricer : public BonusClassicPathPricerBase {
      public:
        /*! \param discountFactor risk-free discount factor from maturity to
                                  the evaluation date
            \pre barrier and bonus level of \p payoff are positive, as
                 BonusClassicOption::arguments::validate() ensures; not
                 checked here.
        */
        BiasedBonusClassicPathPricer(BonusClassicPayoff payoff,
                                     QuantLib::DiscountFactor discountFactor);
        QuantLib::Real operator()(const QuantLib::Path& path) const override;
    };

    //! Path pricer for bonus certificates monitored continuously
    /*! Returns the discounted final price \f$ S_T \f$ of the path if any
        point after \f$ t = 0 \f$ is at or below the barrier \f$ H \f$.
        Otherwise the barrier may still have been crossed between grid
        points; conditional on the endpoints of step \f$ i \f$, the
        log-price is a Brownian bridge and the crossing probability is
        \f[
            p_i = \exp\left(-\frac{2 \ln(S_i/H) \ln(S_{i+1}/H)}{v_i}\right),
        \f]
        where \f$ v_i \f$ is the integrated variance of the step, taken from
        QuantLib::GeneralizedBlackScholesProcess::variance(); \f$ p_i = 0 \f$
        if \f$ v_i \le 0 \f$. With the survival probability
        \f$ P = \prod_i (1 - p_i) \f$ the path pays
        \f[
            S_T + P \left(\max(S_T, B) - S_T\right),
        \f]
        discounted, i.e. its conditional expectation of the payoff of the
        continuously monitored certificate. To the probabilities of
        BonusClassicPathPricerBase a knocked-out path contributes
        \f$ (1, 0) \f$ and a surviving one
        \f[
            \left(1 - P, \; P \, 1_{S_T < B}\right),
        \f]
        its conditional probabilities of a crossing between grid points and
        of the bonus being paid, so that the probabilities are of the
        continuously monitored barrier like the value.

        Unlike QuantLib::BarrierPathPricer it draws no random number of its
        own, so a low-discrepancy path sequence stays intact, and the payoff
        is smooth in the path.

        See P. Glasserman, <i>Monte Carlo Methods in Financial
        Engineering</i>, Springer 2004, on Brownian interpolation of
        barrier crossings, and
        <i>
        Going to Extremes: Correcting Simulation Bias in Exotic
        Option Valuation - D.R. Beaglehole, P.H. Dybvig and G. Zhou
        Financial Analysts Journal; Jan/Feb 1997; 53, 1. pg. 62-68
        </i>
    */
    class BonusClassicPathPricer : public BonusClassicPathPricerBase {
      public:
        /*! \param discountFactor risk-free discount factor from maturity to
                                  the evaluation date
            \param process        the process the paths were generated with;
                                  its variance() gives \f$ v_i \f$
            \pre barrier and bonus level of \p payoff are positive, as
                 BonusClassicOption::arguments::validate() ensures; not
                 checked here.
            \pre \p process is not null; QL_REQUIRE checks this.
        */
        BonusClassicPathPricer(
            BonusClassicPayoff payoff,
            QuantLib::DiscountFactor discountFactor,
            QuantLib::ext::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process);
        QuantLib::Real operator()(const QuantLib::Path& path) const override;

      private:
        QuantLib::ext::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process_;
    };

    //! BonusClassicPathPricer with the step variance from a BlackScholesStepCache
    /*! The same value and the same per-path contributions to the
        probabilities of BonusClassicPathPricerBase as BonusClassicPathPricer
        for paths from CachedStepPathGenerator over the same grid:
        \f$ v_i \f$ is the variance the generator evolved step \f$ i \f$
        with, read from the cache the generator shares instead of from the
        process on every step.
    */
    class CachedStepBonusClassicPathPricer : public BonusClassicPathPricerBase {
      public:
        /*! \param discountFactor risk-free discount factor from maturity to
                                  the evaluation date
            \param stepCache      the cache the paths were generated from
            \pre barrier and bonus level of \p payoff are positive, as
                 BonusClassicOption::arguments::validate() ensures; not
                 checked here.
            \pre \p stepCache is not null and reproduces the process's step,
                 as CachedStepPathGenerator requires; QL_REQUIRE checks both.
        */
        CachedStepBonusClassicPathPricer(
            BonusClassicPayoff payoff,
            QuantLib::DiscountFactor discountFactor,
            QuantLib::ext::shared_ptr<const BlackScholesStepCache> stepCache);
        QuantLib::Real operator()(const QuantLib::Path& path) const override;

      private:
        QuantLib::ext::shared_ptr<const BlackScholesStepCache> stepCache_;
    };


    template <class RNG, class S, template <class> class MC>
    MCBonusClassicEngine<RNG, S, MC>::MCBonusClassicEngine(
        QuantLib::ext::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process,
        QuantLib::Size timeStepsPerYear,
        QuantLib::Size requiredSamples,
        QuantLib::Size maxSamples,
        QuantLib::Real requiredTolerance,
        bool isBiased,
        bool brownianBridge,
        QuantLib::BigNatural seed)
    : QuantLib::McSimulation<MC, RNG, S>(false, false), process_(std::move(process)),
      timeStepsPerYear_(timeStepsPerYear), requiredSamples_(requiredSamples),
      maxSamples_(maxSamples), requiredTolerance_(requiredTolerance), isBiased_(isBiased),
      brownianBridge_(brownianBridge), seed_(seed) {
        // registerWith() accepts a null pointer; calculate() would be the first to dereference it.
        QL_REQUIRE(process_, "null process given");
        // Without this, NPV() keeps returning the first price.
        registerWith(process_);
    }

    template <class RNG, class S, template <class> class MC>
    void MCBonusClassicEngine<RNG, S, MC>::calculate() const {
        const auto spot = process_->x0();
        QL_REQUIRE(spot > 0.0, "negative or null underlying given");
        // Neither pricer inspects path[0]: the biased one because t = 0 is no monitoring date,
        // the continuous one because its bridge needs log(S_0 / H) > 0. Refused in both modes;
        // see the class warning.
        QL_REQUIRE(!triggered(spot), "barrier touched");
        if constexpr (sharesStepCache) {
            // Once per calculation, for pathGenerator() and pathPricer() below; the process
            // may have changed since the last one.
            stepCache_ = QuantLib::ext::make_shared<BlackScholesStepCache>(process_, timeGrid());
        }
        QuantLib::McSimulation<MC, RNG, S>::calculate(requiredTolerance_, requiredSamples_,
                                                      maxSamples_);
        results_.value = this->mcModel_->sampleAccumulator().mean();
        // LowDiscrepancy sets allowsErrorEstimate = 0, and every caller instantiates the engine
        // with it or with traits derived from it.
        if constexpr (RNG::allowsErrorEstimate) {
            results_.errorEstimate = this->mcModel_->sampleAccumulator().errorEstimate();
        }
        // Antithetic variates are off, so the pricer saw every path exactly once and its sums
        // run over the same samples as the accumulator's mean; a pricer recording a path twice
        // would fail here instead of skewing the probabilities silently.
        QL_ENSURE(pathPricer_->samples() == this->mcModel_->sampleAccumulator().samples(),
                  "the path pricer recorded " << pathPricer_->samples() << " paths, the sample "
                                              << "accumulator "
                                              << this->mcModel_->sampleAccumulator().samples());
        results_.additionalResults["barrierHitProbability"] = pathPricer_->barrierHitProbability();
        results_.additionalResults["bonusProbability"] = pathPricer_->bonusProbability();
    }

    template <class RNG, class S, template <class> class MC>
    QuantLib::ext::shared_ptr<typename MCBonusClassicEngine<RNG, S, MC>::path_pricer_type>
    MCBonusClassicEngine<RNG, S, MC>::pathPricer() const {
        const auto payoff =
            QuantLib::ext::dynamic_pointer_cast<BonusClassicPayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "non-plain payoff given");

        const auto grid = timeGrid();
        // Both pricers pay only at maturity; MCBarrierEngine needs a vector of discount
        // factors only for its rebate.
        const auto discountFactor = process_->riskFreeRate()->discount(grid.back());

        // A fresh pricer per calculation: McSimulation::calculate() builds a new model around
        // it, and its sums must not carry over from the last calculation.
        if (isBiased_) {
            pathPricer_ =
                QuantLib::ext::make_shared<BiasedBonusClassicPathPricer>(*payoff, discountFactor);
        } else if constexpr (sharesStepCache) {
            // The traits decide where the bridge's step variance comes from: the cache the
            // paths were built from, or the process the paths were evolved with.
            pathPricer_ = QuantLib::ext::make_shared<CachedStepBonusClassicPathPricer>(
                *payoff, discountFactor, stepCache_);
        } else {
            pathPricer_ = QuantLib::ext::make_shared<BonusClassicPathPricer>(
                *payoff, discountFactor, process_);
        }
        return pathPricer_;
    }


    template <class RNG, class S, template <class> class MC>
    QuantLib::TimeGrid MCBonusClassicEngine<RNG, S, MC>::timeGrid() const {
        // Empty until the instrument's setupArguments() has run, i.e. before the first NPV().
        QL_REQUIRE(arguments_.exercise, "no exercise given");
        if (timeStepsPerYear_ != QuantLib::Null<QuantLib::Size>()) {
            return monitoringGrid(process_->time(arguments_.exercise->lastDate()),
                                  timeStepsPerYear_);
        }
        QL_FAIL("time steps not specified");
    }
}
#endif // MCBONUSCLASSICENGINE_HPP
