name: Apply clang-format fixes

on:
  schedule:
    - cron: '23 2 * * 1'
      timezone: Europe/Berlin
  workflow_dispatch: { }

permissions:
  contents: write
  pull-requests: write

jobs:
  clang-format:
    runs-on: ubuntu-26.04
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: "true"

      - name: Setup Linux variables
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: Setup LLVM
        run: |
          brew update
          brew install llvm@23

      - name: Applying clang-format
        run: git ls-files '*.cpp' '*.hpp' | xargs -r clang-format -i

      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: clang-format-fixes-${{ github.ref_name }}
          base: ${{ github.ref_name }}
          delete-branch: true
          commit-message: "Automated fixes by clang-format"
          title: "Automated fixes by clang-format"
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          body: >
            This is an automated PR generated by the
            [create-pull-request](https://github.com/peter-evans/create-pull-request)
            GitHub action.

            Please review the changes before merging.
