# SPDX-FileCopyrightText: 2024 Ralf Konrad Eckel
# SPDX-License-Identifier: MIT

name: Apply clang-tidy fixes

on:
  schedule:
    - cron: '23 2 * * 1'
      timezone: Europe/Berlin
  workflow_dispatch: { }

permissions:
  contents: write
  pull-requests: write

jobs:
  clang-tidy:
    runs-on: ubuntu-26.04
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: "true"

      - name: Setup needed software
        uses: ./.github/actions/setup
        with:
          os: ubuntu-26.04
          cxx: clang++
          cxx-standard: 17
          save-ccache: 'false'

      - name: Setup LLVM
        run: brew install llvm@23

      - name: Running clang-tidy
        run: |
          cmake --preset clang-tidy -DRKE_CLANG_TIDY_OPTIONS=--fix
          cmake --build --preset clang-tidy -j 1 --verbose

      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: clang-tidy-fixes-${{ github.ref_name }}
          base: ${{ github.ref_name }}
          add-paths: src/**
          delete-branch: true
          commit-message: "Automated fixes by clang-tidy"
          title: "Automated fixes by clang-tidy"
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          body: >
            This is an automated PR generated by the
            [create-pull-request](https://github.com/peter-evans/create-pull-request)
            GitHub action.

            Please review the changes before merging.
