# SPDX-FileCopyrightText: 2024 Ralf Konrad Eckel
# SPDX-License-Identifier: MIT

name: Build and Test with CMake and CTest

on:
  push:
    branches:
      - master
  pull_request: { }
  schedule:
    - cron: '33 0 * * *'
      timezone: Europe/Berlin
  workflow_dispatch: { }

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  cmake-build-and-test:
    strategy:
      fail-fast: false
      matrix:
        settings:
          [
            { os: macos-26,           cc: clang,    cxx: clang++ },

            { os: ubuntu-26.04,       cc: clang,    cxx: clang++ },
            { os: ubuntu-26.04,       cc: gcc,      cxx: g++ },

            { os: ubuntu-26.04-arm,   cc: clang,    cxx: clang++ },
            { os: ubuntu-26.04-arm,   cc: gcc,      cxx: g++ },
            { os: windows-2025,       cc: cl,       cxx: cl }
          ]
        cxx-standard: [ 17, 20, 23 ]
        cmake-preset: [ release ]

    runs-on: ${{ matrix.settings.os }}

    timeout-minutes: ${{ (startsWith(matrix.settings.os, 'windows') && 120) || 60 }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: "true"

      - name: Setup needed software
        id: setup
        uses: ./.github/actions/setup
        with:
          os: ${{ matrix.settings.os }}
          cxx: ${{ matrix.settings.cxx }}
          cxx-standard: ${{ matrix.cxx-standard }}
          save-ccache: ${{ github.ref == 'refs/heads/master' }}

      - name: Configure CMake and Build
        env:
          CC: ${{ matrix.settings.cc }}
          CXX: ${{ matrix.settings.cxx }}
        run: >-
          cmake --version

          cmake --preset ${{ matrix.cmake-preset }}
          -DCMAKE_CXX_STANDARD=${{ matrix.cxx-standard }} -L

          cmake --build --preset ${{ matrix.cmake-preset }} --verbose

      - name: CTest
        run: |
          ctest --version
          ctest --preset ${{ matrix.cmake-preset }} --extra-verbose

  ci-gate:
    needs: cmake-build-and-test
    if: always()
    runs-on: ubuntu-26.04

    timeout-minutes: 5

    steps:
      - name: Check the result of the matrix
        env:
          RESULT: ${{ needs.cmake-build-and-test.result }}
        run: |
          echo "cmake-build-and-test: $RESULT"
          test "$RESULT" = "success"
